version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    command:
      - echo Starting install phase at `date`
  pre_build: # Before Task
    commands:
      - echo Starting pre_build phase at `date`
  build: # Build Task
    commands:
      - echo Build Phase started on `date`
      - zip lambda_function.zip lambda_function.py
      - aws s3 cp lambda_function.zip s3://daisukeshimizu/
  post_build: # after Build Task
    commands:
      - echo Post Build Phase started on `date`
#artifacts: # Deliverables
#  files:
#    - ./lambda_function.zip
